let audio = document.getElementById('themeSong');
audio.volume = 0.01;

//Guessing Game
const characters = [
    'Reimu Hakurei',
    'Marisa Kirisame',
    'Rumia',
    'Daiyousei',
    'Cirno',
    'Hong Meiling',
    'Koakuma',
    'Patchouli Knowledge',
    'Sakuya Izayoi',
    'Remilia Scarlet',
    'Flandre Scarlet',
    'Letty Whiterock',
    'Chen',
    'Alice Margatroid',
    'Lily White',
    'Lunasa Prismriver',
    'Merlin Prismriver',
    'Lyrica Prismriver',
    'Youmu Konpaku',
    'Yuyuko Saigyouji',
    'Ran Yakumo',
    'Yukari Yakumo',
    'Suika Ibuki',
    'Wriggle Nightbug',
    'Mystia Lorelei',
    'Keine Kamishirasawa',
    'Tewi Inaba',
    'Reisen Udongein Inaba',
    'Eirin Yagokoro',
    'Kaguya Houraisan',
    'Fujiwara no Mokou',
    'Aya Shameimaru',
    'Medicine Melancholy',
    'Yuuka Kazami',
    'Komachi Onozuka',
    'Shiki Eiki',
    'Shizuha Aki',
    'Minoriko Aki',
    'Hina Kagiyama',
    'Nitori Kawashiro',
    'Momiji Inubashiri',
    'Sanae Kochiya',
    'Kanako Yasaka',
    'Suwako Moriya',
    'Iku Nagae',
    'Tenshi Hinanawi',
    'Kisume',
    'Yamame Kurodani',
    'Parsee Mizuhashi',
    'Yuugi Hoshiguma',
    'Satori Komeiji',
    'Orin Kaenbyou',
    'Utsuho Reiuji',
    'Koishi Komeiji',
    'Nazrin',
    'Kogasa Tatara',
    'Ichirin Kumoi',
    'Minamitsu Murasa',
    'Shou Toramaru',
    'Byakuren Hijiri',
    'Nue Houjuu',
    'Hatate Himekaidou',
    'Kyokou Kasodani',
    'Yoshika Miyako',
    'Seiga Kaku',
    'Soga no Tojiko',
    'Mononobe no Futo',
    'Toyosatomimi no Miko',
    'Mamizou Futatsuiwa',
    'Hata no Kokoro',
    'Wakasagihime',
    'Sekibanki',
    'Kagerou Imaizumi',
    'Benben Tsukumo',
    'Yatsuhashi Tsukumo',
    'Seija Kijin',
    'Shinmyoumaru Sukuna',
    'Raiko Horikawa',
    'Sumireko Usami',
    'Seiran',
    'Ringo',
    'Doremy Sweet',
    'Sagume Kishin',
    'Clownpiece',
    'Junko',
    'Hecatia Lapislazuli',
    'Joon Yorigami',
    'Shion Yorigami'
]